export const FETCH_USER = "FETCH_USER";
export const REQUEST_ADD_USER = "REQUEST_ADD_USER";
export const RECEIVE_ADD_USER = "RECEIVE_ADD_USER";
export const REQUEST_ERROR = "REQUEST_ERROR";
export const ADD_ADVENTURE = "ADD_ADVENTURE";
export const DEL_ADVENTURE = "DEL_ADVENTURE";
export const PICK_ADVENTURE = "PICK_ADVENTURE";
