// USERS
export const FETCH_USER = "FETCH_USER";
export const LOGOUT = "LOGOUT";
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const RECEIVE_LOGIN = "RECEIVE_LOGIN";
export const RECEIVE_LOGIN_ERROR = "RECEIVE_LOGIN_ERROR";
export const REQUEST_ADD_USER = "REQUEST_ADD_USER";
export const RECEIVE_ADD_USER = "RECEIVE_ADD_USER";
export const REQUEST_ERROR = "REQUEST_ERROR";

// ADVENTURES
export const REQUEST_GET_ADVENTURES = "REQUEST_GET_ADVENTURES";
export const RECEIVE_GET_ADVENTURES = "RECEIVE_GET_ADVENTURES";
export const REQUEST_ADD_ADVENTURE = "REQUEST_ADD_ADVENTURE";
export const RECEIVE_ADD_ADVENTURE = "RECEIVE_ADD_ADVENTURE";
export const RECEIVE_DEL_ADVENTURE = "RECEIVE_DEL_ADVENTURE";
export const REQUEST_EDIT_ADVENTURE = "REQUEST_EDIT_ADVENTURE";
export const RECEIVE_EDIT_ADVENTURE = "RECEIVE_EDIT_ADVENTURE";
export const DEL_ADVENTURE = "DEL_ADVENTURE";
export const PICK_ADVENTURE = "PICK_ADVENTURE";
export const SET_EDIT = "SET_EDIT";
export const UNSET_EDIT = "UNSET_EDIT";
export const SET_SESSION = "SET_SESSION";
export const BEGIN_SESSION = "BEGIN_SESSION";
export const RECEIVE_GET_PLAYERS = "RECEIVE_GET_PLAYERS";
export const REQUEST_GET_PLAYERS = "REQUEST_GET_PLAYERS";


// COMBAT
export const NEW_EVENT = "NEW_EVENT";
export const BEGIN_COMBAT = "BEGIN_COMBAT";
export const FINISH_COMBAT = "FINISH_COMBAT";

// SESSION
export const CLEAR_NEWS = "CLEAR_NEWS";
export const TOGGLE_HERO = "TOGGLE_HERO";
export const CONFIGURE_COMBAT = "CONFIGURE_COMBAT";
export const ADD_ENEMY = "ADD_ENEMY";
export const PICK_ENEMY = "PICK_ENEMY";
export const REMOVE_ENEMY = "REMOVE_ENEMY";
export const CANCEL = "CANCEL";
